---
name: publish

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    publish-docker-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            
      
            - name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
                with:
                images: my-docker-hub-namespace/my-docker-hub-repository
            
            - name: Build and push Docker image
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

